<select class="form-control" name="car_percentage" id="car_percentage" onchange="mortgageDebtCalculate()">
    <option value="0" {{ $purchaseTsa->car_percentage == 0 ? 'selected' : '' }}>0</option>
    <option value="10" {{ $purchaseTsa->car_percentage == 10 ? 'selected' : '' }}>10</option>
    <option value="11" {{ $purchaseTsa->car_percentage == 11 ? 'selected' : '' }}>11</option>
    <option value="12" {{ $purchaseTsa->car_percentage == 12 ? 'selected' : '' }}>12</option>
    <option value="13" {{ $purchaseTsa->car_percentage == 13 ? 'selected' : '' }}>13</option>
    <option value="14" {{ $purchaseTsa->car_percentage == 14 ? 'selected' : '' }}>14</option>
    <option value="15" {{ $purchaseTsa->car_percentage == 15 ? 'selected' : '' }}>15</option>
    <option value="16" {{ $purchaseTsa->car_percentage == 16 ? 'selected' : '' }}>16</option>
    <option value="17" {{ $purchaseTsa->car_percentage == 17 ? 'selected' : '' }}>17</option>
    <option value="18" {{ $purchaseTsa->car_percentage == 18 ? 'selected' : '' }}>18</option>
    <option value="19" {{ $purchaseTsa->car_percentage == 19 ? 'selected' : '' }}>19</option>
    <option value="20" {{ $purchaseTsa->car_percentage == 20 ? 'selected' : '' }}>20</option>
    <option value="21" {{ $purchaseTsa->car_percentage == 21 ? 'selected' : '' }}>21</option>
    <option value="22" {{ $purchaseTsa->car_percentage == 22 ? 'selected' : '' }}>22</option>
    <option value="23" {{ $purchaseTsa->car_percentage == 23 ? 'selected' : '' }}>23</option>
    <option value="24" {{ $purchaseTsa->car_percentage == 24 ? 'selected' : '' }}>24</option>
    <option value="25" {{ $purchaseTsa->car_percentage == 25 ? 'selected' : '' }}>25</option>
    <option value="26" {{ $purchaseTsa->car_percentage == 26 ? 'selected' : '' }}>26</option>
    <option value="27" {{ $purchaseTsa->car_percentage == 27 ? 'selected' : '' }}>27</option>
    <option value="28" {{ $purchaseTsa->car_percentage == 28 ? 'selected' : '' }}>28</option>
    <option value="29" {{ $purchaseTsa->car_percentage == 29 ? 'selected' : '' }}>29</option>
    <option value="30" {{ $purchaseTsa->car_percentage == 30 ? 'selected' : '' }}>30</option>
    <option value="31" {{ $purchaseTsa->car_percentage == 31 ? 'selected' : '' }}>31</option>
    <option value="32" {{ $purchaseTsa->car_percentage == 32 ? 'selected' : '' }}>32</option>
    <option value="33" {{ $purchaseTsa->car_percentage == 33 ? 'selected' : '' }}>33</option>
    <option value="34" {{ $purchaseTsa->car_percentage == 34 ? 'selected' : '' }}>34</option>
    <option value="35" {{ $purchaseTsa->car_percentage == 35 ? 'selected' : '' }}>35</option>
    <option value="36" {{ $purchaseTsa->car_percentage == 36 ? 'selected' : '' }}>36</option>
    <option value="37" {{ $purchaseTsa->car_percentage == 37 ? 'selected' : '' }}>37</option>
    <option value="38" {{ $purchaseTsa->car_percentage == 38 ? 'selected' : '' }}>38</option>
    <option value="39" {{ $purchaseTsa->car_percentage == 39 ? 'selected' : '' }}>39</option>
    <option value="40" {{ $purchaseTsa->car_percentage == 40 ? 'selected' : '' }}>40</option>
    <option value="41" {{ $purchaseTsa->car_percentage == 41 ? 'selected' : '' }}>41</option>
    <option value="42" {{ $purchaseTsa->car_percentage == 42 ? 'selected' : '' }}>42</option>
    <option value="43" {{ $purchaseTsa->car_percentage == 43 ? 'selected' : '' }}>43</option>
    <option value="44" {{ $purchaseTsa->car_percentage == 44 ? 'selected' : '' }}>44</option>
    <option value="45" {{ $purchaseTsa->car_percentage == 45 ? 'selected' : '' }}>45</option>
    <option value="46" {{ $purchaseTsa->car_percentage == 46 ? 'selected' : '' }}>46</option>
    <option value="47" {{ $purchaseTsa->car_percentage == 47 ? 'selected' : '' }}>47</option>
    <option value="48" {{ $purchaseTsa->car_percentage == 48 ? 'selected' : '' }}>48</option>
    <option value="49" {{ $purchaseTsa->car_percentage == 49 ? 'selected' : '' }}>49</option>
    <option value="50" {{ $purchaseTsa->car_percentage == 50 ? 'selected' : '' }}>50</option>
</select>
